### ISSUE TITLE
PosixPath doesn't work with redirections

### ISSUE THREAD

**Issue by elkarouh** [kbairak/pipepy#9]
Redirection works with strings and file-like objects. 
It should work with Path objects too.

```python
>>> from pipepy import ls
>>> ls > "deleteme"
>>> from pathlib import Path
>>> ls > Path("deleteme")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'PipePy' and 'PosixPath'
```

**Comment by kbairak** [comment]
Nice catch. I will get on it

**Comment by kbairak** [comment]
Hey @elkarouh . I opened a PR that implements what you asked. Do you want to take a look before I publish it? Perhaps I missed another use-case.
